pipeline:
  build:
    group: build
    image: node:latest
    commands:
      - npm test

  deploy:
    image: gitlab/dind
    privileged: true
    commands:
      - DOCKER_API_VERSION=1.23 docker build -t callebjorkell/cuddle-cake .

