pipeline:
  build:
    group: build
    image: node:latest
    commands:
      - npm test

  deploy:
    image: gitlab/dind
    privileged: true
    commands:
      - docker build -t callebjorkell/cuddle-cake .

