pipeline:
  build:
    group: build
    image: node:latest
    commands:
      - npm test

  push:
    image: gitlab/dind
    privileged: true
    commands:
      - DOCKER_API_VERSION=1.23 docker build -t 127.0.0.1:30400/cuddle-cake .
      - DOCKER_API_VERSION=1.23 docker push 127.0.0.1:30400/cuddle-cake

  deploy:
    image: nrgizer/helm-test
    commands:
      - /usr/bin/helm-test tiller-deploy.kube-system.svc.cluster.local:44134 /share/go/src/callebjorkell/cuddle-cake/charts/cuddle-cake
