apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cuddle-cake
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}

spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 2
  progressDeadlineSeconds: 10
  template:
    metadata:
      labels:
        service: cuddle-cake
        # add random string, to force re-start of pods
        random-string: {{ randAlphaNum 15 }}
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-cuddle-cake-env-config
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        name: cuddle-cake
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: cuddle-cake
  name: cuddle-cake
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 9001
  selector:
    service: cuddle-cake
